= Install Alpine Linux in nspawn
:script-name: alpine-nspawn-install
:script-sha256: 2178fa233df43c360d45880c4dbd74bf8d2b71e307ea5bdda1b84468815d16cd
:gh-name: quantum5/{script-name}
:version: 0.0.1

ifdef::env-github[]
image:https://github.com/{gh-name}/workflows/CI/badge.svg["Build Status", link="https://github.com/{gh-name}/actions"]
endif::env-github[]

This `alpine-nspawn-install` script simplifies installation of https://alpinelinux.org/[Alpine Linux] inside `systemd-nspawn`.

Installation of Alpine Linux is a matter of a few seconds… *5 seconds* to be more specific.
It takes just ~5 seconds to prepare a nspawn image, and it doesn’t use any prebuilt rootfs archive or image, and no Docker, of course.
All you need to install Alpine Linux is just https://github.com/alpinelinux/apk-tools[apk-tools] -- Alpine’s package manager -- which is automatically downloaded by this script.

This is based on https://github.com/alpinelinux/alpine-chroot-install.

== Requirements

* Linux system with common userland (Busybox or GNU coreutils)
* POSIX-sh compatible shell (e.g. Busybox ash, dash, Bash, ZSH)

== Usage

Read documentation in link:{script-name}[{script-name}].

You can copy link:{script-name}[{script-name}] into your repository or download it on demand, e.g.:

[source, sh, subs="verbatim, attributes"]
wget https://raw.githubusercontent.com/{gh-name}/v{version}/{script-name} \
    && echo '{script-sha256}  {script-name}' | sha256sum -c \
    || exit 1

== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
